# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a9f91428d5f8e4ea57cef1d5d4d71251645d7b4bef84cd3777251695f74ba5d9eafa79ba0f6e17a3842033c18424f31a11b09e684f651dfa0df60858d6594d4

test:
  secret_key_base: 5d3877e10f11a169ce81b7f338bbdd7a764fd92af9987e73bf1d9fb1b34b57c2282474202614e26622f4ea43d15210b0a5b50a67b8b60dc3f00c0b7e693cef09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
